# Durable block-Gibbs gold references for the Z-ratio surface bands.
#
# Gold at the large sizes is expensive (a size-150 CN block costs ~90 s per
# replicate at 2000 sweeps), and the same bands get re-scored whenever the
# surface changes: extension rule, cap raise, and the alpha != 1 validation all
# want them. This banks every reference that has been paid for, keyed on the
# cell, the block descriptor, and the Monte-Carlo budget, so a re-score costs a
# lookup instead of a rerun.
#
# The bank is additive: gold_bank() returns cached rows when the key matches and
# computes (and stores) only what is missing. Delete the RDS to force a rebuild.
#
# Blocks are the canonical single-component ones: a CN clique of `size` nodes
# adjacent to both endpoints, or a near-balanced bipartite bridge, both at
# density 1. The generators live here so a banked row is reproducible from this
# file alone.

# Location of the bank; BGMS_GOLD_BANK overrides it for a scratch run.
gold_bank_path = function() {
  p = Sys.getenv("BGMS_GOLD_BANK", "")
  if(nzchar(p)) p else "dev/validation/zratio_gold_bank.rds"
}

gold_block = function(family, size) {
  q = size + 2L
  G = matrix(0L, q, q)
  if(family == "cn") {
    for(v in 3:q) G[1, v] = G[v, 1] = G[2, v] = G[v, 2] = 1L
    for(a in 3:(q - 1)) for(b in (a + 1):q) G[a, b] = G[b, a] = 1L
  } else {
    na_ = size %/% 2L
    A = 2L + seq_len(na_)
    B = setdiff(3:q, A)
    for(v in A) G[1, v] = G[v, 1] = 1L
    for(v in B) G[2, v] = G[v, 2] = 1L
    for(a in A) for(b in B) G[a, b] = G[b, a] = 1L
  }
  G
}

gold_bank_key = function(cell, family, size, sweeps, burn, seed) {
  sprintf(
    "%s|d%.8g|e%.8g|a%.8g|%s|n%d|s%d|b%d|sd%d",
    family, cell$delta, cell$eta, cell$alpha, cell$slab, size, sweeps, burn, seed
  )
}

# Returns a data frame with one row per (family, size): mean, sd, se, n_reps.
# Computes and banks any missing replicate.
gold_bank = function(zc, cell, family, sizes, sweeps, burn, seeds,
                     verbose = TRUE) {
  path = gold_bank_path()
  bank = if(file.exists(path)) readRDS(path) else list()
  dirty = FALSE
  rows = lapply(sizes, function(size) {
    vals = vapply(seeds, function(sd_) {
      key = gold_bank_key(cell, family, size, sweeps, burn, sd_)
      if(!is.null(bank[[key]])) return(bank[[key]])
      G = gold_block(family, size)
      t0 = proc.time()[["elapsed"]]
      g = bgms:::zratio_test_gold_moments(
        G, 1, 2, zc$addc, zc$tg, zc$ihat, zc$ghat, zc$wt, zc$psi0,
        zc$delta, zc$eta, as.integer(sweeps), as.integer(burn),
        as.integer(sd_), identical(cell$slab, "cauchy"), cell$alpha
      )
      v = if(!isTRUE(g$valid)) NA_real_ else g$logR
      bank[[key]] <<- v
      dirty <<- TRUE
      if(verbose) {
        cat(sprintf("  gold %s k=%d seed=%d -> %.4f (%.0fs)\n", family, size,
                    sd_, v, proc.time()[["elapsed"]] - t0))
        utils::flush.console()
      }
      v
    }, numeric(1))
    data.frame(
      family = family, size = size, sweeps = sweeps, burn = burn,
      n_reps = length(vals), mean = mean(vals), sd = stats::sd(vals),
      se = stats::sd(vals) / sqrt(length(vals))
    )
  })
  if(dirty) {
    dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
    saveRDS(bank, path)
  }
  do.call(rbind, rows)
}

# Human-readable manifest of everything banked, written next to the RDS.
gold_bank_manifest = function() {
  path = gold_bank_path()
  if(!file.exists(path)) {
    return(invisible(NULL))
  }
  bank = readRDS(path)
  parts = do.call(rbind, lapply(names(bank), function(k) {
    f = strsplit(k, "|", fixed = TRUE)[[1]]
    data.frame(
      family = f[1], delta = f[2], eta = f[3], alpha = f[4], slab = f[5],
      size = as.integer(sub("^n", "", f[6])),
      sweeps = as.integer(sub("^s", "", f[7])),
      burn = as.integer(sub("^b", "", f[8])),
      seed = as.integer(sub("^sd", "", f[9])),
      logR = bank[[k]]
    )
  }))
  agg = stats::aggregate(
    logR ~ family + delta + eta + alpha + slab + size + sweeps + burn,
    data = parts, FUN = function(v) c(n = length(v), m = mean(v), s = stats::sd(v))
  )
  out = data.frame(
    agg[, c("family", "delta", "eta", "alpha", "slab", "size", "sweeps", "burn")],
    n_reps = agg$logR[, "n"], mean = agg$logR[, "m"], sd = agg$logR[, "s"]
  )
  out = out[order(out$family, out$eta, out$alpha, out$size), ]
  md = file.path(dirname(path), "zratio_gold_bank.md")
  writeLines(
    c(
      "# Z-ratio block-Gibbs gold bank",
      "",
      "Generated by `dev/validation/zratio_gold_bank.R`. One row per",
      "(family, cell, block size, budget); `sd` is the spread across",
      "replicate seeds and bounds what any claim against these references can",
      "resolve. Blocks are single-component at density 1.",
      "",
      knitr_kable(out)
    ),
    md
  )
  invisible(out)
}

# Minimal markdown table writer so the manifest has no package dependency.
knitr_kable = function(df) {
  fmt = function(x) if(is.numeric(x)) formatC(x, format = "g", digits = 6) else as.character(x)
  head = paste0("| ", paste(names(df), collapse = " | "), " |")
  rule = paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|")
  body = apply(df, 1, function(r) paste0("| ", paste(fmt(r), collapse = " | "), " |"))
  c(head, rule, body)
}
