# Companion script: estimation-to-evidence
# Generated from examples/estimation-to-evidence.qmd by scripts/extract-example-code.R.
# Do not edit this file; edit the page and re-render.

library(bgms)

fit = bgm(Wenchuan, iter = 1e4, warmup = 5e3, seed = 123)

library(qgraph)

wenchuan = Wenchuan[complete.cases(Wenchuan), ]
correlations = cor_auto(wenchuan)
glasso = EBICglasso(S = correlations, n = nrow(wenchuan), gamma = 0.5)

sum(glasso[upper.tri(glasso)] != 0)
glasso["intrusion", "concen"]

bf = extract_inclusion_bf(fit)
bf["intrusion", "concen"]

verdicts(fit)

library(qgraph)

plot_edge_evidence = function(fit, labels, node_color, threshold = 10,
                              seed = 1234, vsize = 9) {
  bf = extract_inclusion_bf(fit)
  weights = coef(fit)$pairwise

  presence = bf >= threshold
  absence = bf <= 1 / threshold
  undecided = !presence & !absence
  diag(presence) = diag(absence) = diag(undecided) = FALSE

  # One layout, computed from every pair, so the three panels match node
  # for node.
  set.seed(seed)
  shared = qgraph(abs(weights), layout = "spring", repulsion = 0.9,
                  DoNotPlot = TRUE)$layout

  panel = function(edges, label, count, ...) {
    qgraph(edges, layout = shared, labels = labels, fade = FALSE,
           color = node_color, vsize = vsize, label.scale.equal = TRUE,
           border.color = "grey30", mar = c(3, 4, 8, 4), ...)
    mtext(sprintf("%s: %d", label, count), side = 3, line = 1.2,
          cex = 0.95, font = 2)
  }

  par(mfrow = c(1, 3))
  panel(weights * presence, "evidence of presence", sum(presence) / 2,
        theme = "TeamFortress", edge.width = 1.1)
  panel(absence * 1, "evidence of absence", sum(absence) / 2,
        edge.color = "#A66A1E", lty = 2, edge.width = 1.1)
  panel(undecided * 1, "undecided", sum(undecided) / 2,
        edge.color = "#8A8578", lty = 3, edge.width = 1.4)
}

plot_edge_evidence(fit, colnames(Wenchuan), "#f0ae0e")

w = extract_pairwise_interactions(fit)[, "intrusion-concen"]
round(c(mean = mean(w), quantile(w, c(0.025, 0.975))), 2)
