# Companion script: reading-the-output
# Generated from examples/reading-the-output.qmd by scripts/extract-example-code.R.
# Do not edit this file; edit the page and re-render.

library(bgms)

fit = bgm(Wenchuan, iter = 1e4, warmup = 5e3, seed = 123)

summary(fit)
