# Companion script: check-your-priors
# Generated from examples/check-your-priors.qmd by scripts/extract-example-code.R.
# Do not edit this file; edit the page and re-render.

library(bgms)

fit = bgm(Wenchuan, iter = 1e4, warmup = 5e3, seed = 123)
ps = prior_sensitivity_check(fit, seed = 123)

ps

plot(ps)
