# Companion script: comparing-groups
# Generated from examples/comparing-groups.qmd by scripts/extract-example-code.R.
# Do not edit this file; edit the page and re-render.

library(bgms)

fit = bgmCompare(
  x = ADHD[, -1],
  group_indicator = ADHD$group,
  variable_type = "ordinal",
  seed = 123
)

plot(fit)

verdicts(fit)

bf = extract_inclusion_bf(fit)
bf["motor", "seat"]
coef(fit)$pairwise_effects_groups["motor-seat", ]

table(verdicts(fit, evidence_threshold = 3)$verdict)
