# Companion script: edge-clustering
# Generated from examples/edge-clustering.qmd by scripts/extract-example-code.R.
# Do not edit this file; edit the page and re-render.

library(bgms)

martarelli = readRDS(url(
  "https://bayesian-graphical-modelling-lab.github.io/bgms/data/martarelli.rds"
))
items = as.data.frame(martarelli[, 3:20])

fit = bgm(items, edge_prior = sbm_prior(), iter = 2e4, warmup = 1e4,
          seed = 123)

sbm = extract_sbm(fit)
round(head(sbm$posterior_num_blocks, 4), 3)

p = sbm$posterior_num_blocks$probability
names(p) = rownames(sbm$posterior_num_blocks)
round(c(
  # H1: some clustering (B > 1) vs H0: none; prior odds exp(lambda) - 1
  clustering   = ((1 - p["1"]) / p["1"]) / (exp(1) - 1),
  # H1: B = 2 vs H2: B = 1; prior odds 1 at lambda = 1
  two_vs_one   = p["2"] / p["1"],
  # H1: B = 2 vs H2: B = 3; prior odds 2 at lambda = 1
  two_vs_three = (p["2"] / p["3"]) / 2
), 2)

split(rownames(sbm$posterior_mean_coclustering_matrix),
      sbm$posterior_mode_allocations)

cm = sbm$posterior_mean_coclustering_matrix
z = sbm$posterior_mode_allocations
same = outer(z, z, "==")[upper.tri(cm)]
cc = cm[upper.tri(cm)]
round(rbind(within = range(cc[same]), between = range(cc[!same])), 2)

p = nrow(cm)
op = par(mar = c(6.5, 6.5, 1, 1))
image(1:p, 1:p, cm[, p:1], col = hcl.colors(20, "Blues", rev = TRUE),
      axes = FALSE, xlab = "", ylab = "")
axis(1, at = 1:p, labels = rownames(cm), las = 2, cex.axis = 0.7)
axis(2, at = p:1, labels = colnames(cm), las = 1, cex.axis = 0.7)
par(op)

table(verdicts(fit)$verdict)
