# Companion script: from-bootnet-qgraph
# Generated from examples/from-bootnet-qgraph.qmd by scripts/extract-example-code.R.
# Do not edit this file; edit the page and re-render.

library(bgms)

# Fit once; everything else reads from the fit.
fit = bgm(Wenchuan, iter = 1e4, warmup = 5e3, seed = 123)

# The network, split by evidence, and the verdict table behind it.
plot(fit)
verdicts(fit)

# Edge weights with credible intervals.
summary(fit)$pairwise

# The difference between two edges, as a posterior.
w = extract_pairwise_interactions(fit)
quantile(w[, "intrusion-dreams"] - w[, "intrusion-upset"],
         c(0.025, 0.975))

# Centrality with uncertainty.
plot(extract_centrality(fit))

# Do the conditional predictions hold up?
calibration_check(fit, seed = 123)
